/**
 * Arduino IoT Cloud API
 * Provides a set of endpoints to manage Arduino IoT Cloud **Devices**, **Things**, **Properties** and **Timeseries**. This API can be called just with any HTTP Client, or using one of these clients:  * [Javascript NPM package](https://www.npmjs.com/package/@arduino/arduino-iot-client)  * [Python PYPI Package](https://pypi.org/project/arduino-iot-client/)  * [Golang Module](https://github.com/arduino/iot-client-go)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';


class ArduinoLorafreqplanv1 {
    
    constructor() { 
        ArduinoLorafreqplanv1.initialize(this);
    }

    
    static initialize(obj) { 
        obj['advanced'] = advanced;
        obj['id'] = id;
        obj['name'] = name;
    }

    
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ArduinoLorafreqplanv1();

            if (data.hasOwnProperty('advanced')) {
                obj['advanced'] = data.advanced;
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = data.id;
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = data.name;
            }
        }
        return obj;
    }

    
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ArduinoLorafreqplanv1.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }

        return true;
    }


}

ArduinoLorafreqplanv1.RequiredProperties = ["advanced", "id", "name"];


ArduinoLorafreqplanv1.prototype['advanced'] = undefined;


ArduinoLorafreqplanv1.prototype['id'] = undefined;


ArduinoLorafreqplanv1.prototype['name'] = undefined;






export default ArduinoLorafreqplanv1;

