/**
 * Arduino IoT Cloud API
 * Provides a set of endpoints to manage Arduino IoT Cloud **Devices**, **Things**, **Properties** and **Timeseries**. This API can be called just with any HTTP Client, or using one of these clients:  * [Javascript NPM package](https://www.npmjs.com/package/@arduino/arduino-iot-client)  * [Python PYPI Package](https://pypi.org/project/arduino-iot-client/)  * [Golang Module](https://github.com/arduino/iot-client-go)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';


class ArduinoDevicev2Pass {
    
    constructor() { 
        ArduinoDevicev2Pass.initialize(this);
    }

    
    static initialize(obj) { 
        obj['set'] = set;
    }

    
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ArduinoDevicev2Pass();

            if (data.hasOwnProperty('set')) {
                obj['set'] = data.set;
            }
            if (data.hasOwnProperty('suggested_password')) {
                obj['suggested_password'] = data.suggested_password;
            }
        }
        return obj;
    }

    
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ArduinoDevicev2Pass.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['suggested_password'] && !(typeof data['suggested_password'] === 'string' || data['suggested_password'] instanceof String)) {
            throw new Error("Expected the field `suggested_password` to be a primitive type in the JSON string but got " + data['suggested_password']);
        }

        return true;
    }


}

ArduinoDevicev2Pass.RequiredProperties = ["set"];


ArduinoDevicev2Pass.prototype['set'] = undefined;


ArduinoDevicev2Pass.prototype['suggested_password'] = undefined;






export default ArduinoDevicev2Pass;

