/**
 * Arduino IoT Cloud API
 * Provides a set of endpoints to manage Arduino IoT Cloud **Devices**, **Things**, **Properties** and **Timeseries**. This API can be called just with any HTTP Client, or using one of these clients:  * [Javascript NPM package](https://www.npmjs.com/package/@arduino/arduino-iot-client)  * [Python PYPI Package](https://pypi.org/project/arduino-iot-client/)  * [Golang Module](https://github.com/arduino/iot-client-go)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import from openapi_client.models.arduino_thingresult import ArduinoThingresult from './from openapi_client.models.arduino_thingresult import ArduinoThingresult';


class ArduinoTemplate {
    
    constructor() { 
        ArduinoTemplate.initialize(this);
    }

    
    static initialize(obj) { 
        obj['things'] = things;
    }

    
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ArduinoTemplate();

            if (data.hasOwnProperty('dashboards')) {
                obj['dashboards'] = data.dashboards;
            }
            if (data.hasOwnProperty('things')) {
                obj['things'] = data.things;
            }
            if (data.hasOwnProperty('triggers')) {
                obj['triggers'] = data.triggers;
            }
        }
        return obj;
    }

    
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ArduinoTemplate.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is an array
        if (!Array.isArray(data['dashboards'])) {
            throw new Error("Expected the field `dashboards` to be an array in the JSON data but got " + data['dashboards']);
        }
        if (data['things']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['things'])) {
                throw new Error("Expected the field `things` to be an array in the JSON data but got " + data['things']);
            }
            // validate the optional field `things` (array)
            for (const item of data['things']) {
                ArduinoThingresult.validateJSON(item);
            };
        }
        // ensure the json data is an array
        if (!Array.isArray(data['triggers'])) {
            throw new Error("Expected the field `triggers` to be an array in the JSON data but got " + data['triggers']);
        }

        return true;
    }


}

ArduinoTemplate.RequiredProperties = ["things"];


ArduinoTemplate.prototype['dashboards'] = undefined;


ArduinoTemplate.prototype['things'] = undefined;


ArduinoTemplate.prototype['triggers'] = undefined;






export default ArduinoTemplate;

