/**
 * Arduino IoT Cloud API
 * Provides a set of endpoints to manage Arduino IoT Cloud **Devices**, **Things**, **Properties** and **Timeseries**. This API can be called just with any HTTP Client, or using one of these clients:  * [Javascript NPM package](https://www.npmjs.com/package/@arduino/arduino-iot-client)  * [Python PYPI Package](https://pypi.org/project/arduino-iot-client/)  * [Golang Module](https://github.com/arduino/iot-client-go)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';


class CreateDevicesV2CertsPayload {
    
    constructor() { 
        CreateDevicesV2CertsPayload.initialize(this);
    }

    
    static initialize(obj) { 
        obj['csr'] = csr;
        obj['enabled'] = enabled;
    }

    
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateDevicesV2CertsPayload();

            if (data.hasOwnProperty('ca')) {
                obj['ca'] = data.ca;
            }
            if (data.hasOwnProperty('csr')) {
                obj['csr'] = data.csr;
            }
            if (data.hasOwnProperty('enabled')) {
                obj['enabled'] = data.enabled;
            }
        }
        return obj;
    }

    
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CreateDevicesV2CertsPayload.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['ca'] && !(typeof data['ca'] === 'string' || data['ca'] instanceof String)) {
            throw new Error("Expected the field `ca` to be a primitive type in the JSON string but got " + data['ca']);
        }
        // ensure the json data is a string
        if (data['csr'] && !(typeof data['csr'] === 'string' || data['csr'] instanceof String)) {
            throw new Error("Expected the field `csr` to be a primitive type in the JSON string but got " + data['csr']);
        }

        return true;
    }


}

CreateDevicesV2CertsPayload.RequiredProperties = ["csr", "enabled"];


CreateDevicesV2CertsPayload.prototype['ca'] = undefined;


CreateDevicesV2CertsPayload.prototype['csr'] = undefined;


CreateDevicesV2CertsPayload.prototype['enabled'] = undefined;






export default CreateDevicesV2CertsPayload;

