/**
 * Arduino IoT Cloud API
 * Provides a set of endpoints to manage Arduino IoT Cloud **Devices**, **Things**, **Properties** and **Timeseries**. This API can be called just with any HTTP Client, or using one of these clients:  * [Javascript NPM package](https://www.npmjs.com/package/@arduino/arduino-iot-client)  * [Python PYPI Package](https://pypi.org/project/arduino-iot-client/)  * [Golang Module](https://github.com/arduino/iot-client-go)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';


class PropertyValue {
    
    constructor() { 
        PropertyValue.initialize(this);
    }

    
    static initialize(obj) { 
        obj['value'] = value;
    }

    
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PropertyValue();

            if (data.hasOwnProperty('device_id')) {
                obj['device_id'] = data.device_id;
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = data.value;
            }
        }
        return obj;
    }

    
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PropertyValue.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['device_id'] && !(typeof data['device_id'] === 'string' || data['device_id'] instanceof String)) {
            throw new Error("Expected the field `device_id` to be a primitive type in the JSON string but got " + data['device_id']);
        }

        return true;
    }


}

PropertyValue.RequiredProperties = ["value"];


PropertyValue.prototype['device_id'] = undefined;


PropertyValue.prototype['value'] = undefined;






export default PropertyValue;

