/**
 * Arduino IoT Cloud API
 * Provides a set of endpoints to manage Arduino IoT Cloud **Devices**, **Things**, **Properties** and **Timeseries**. This API can be called just with any HTTP Client, or using one of these clients:  * [Javascript NPM package](https://www.npmjs.com/package/@arduino/arduino-iot-client)  * [Python PYPI Package](https://pypi.org/project/arduino-iot-client/)  * [Golang Module](https://github.com/arduino/iot-client-go)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ArduinoLinkedvariable from './ArduinoLinkedvariable';

/**
 * The ArduinoWidgetv3 model module.
 * @module model/ArduinoWidgetv3
 * @version 3.1.3
 */
class ArduinoWidgetv3 {
    /**
     * Constructs a new <code>ArduinoWidgetv3</code>.
     * ArduinoWidgetv3 media type (default view)
     * @alias module:model/ArduinoWidgetv3
     * @param height {Number} Widget current height for desktop
     * @param id {String} The UUID of the widget, set by client
     * @param options {Object.<String, Object>} Widget options
     * @param pageId {String} The ID of the page the widget belongs to, \"0\" if it's in the main page
     * @param type {String} The type of the widget
     * @param width {Number} Widget current width for desktop
     * @param x {Number} Widget x position for desktop
     * @param y {Number} Widget y position for desktop
     */
    constructor(height, id, options, pageId, type, width, x, y) { 
        
        ArduinoWidgetv3.initialize(this, height, id, options, pageId, type, width, x, y);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, height, id, options, pageId, type, width, x, y) { 
        obj['height'] = height;
        obj['id'] = id;
        obj['options'] = options;
        obj['page_id'] = pageId;
        obj['type'] = type;
        obj['width'] = width;
        obj['x'] = x;
        obj['y'] = y;
    }

    /**
     * Constructs a <code>ArduinoWidgetv3</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ArduinoWidgetv3} obj Optional instance to populate.
     * @return {module:model/ArduinoWidgetv3} The populated <code>ArduinoWidgetv3</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ArduinoWidgetv3();

            if (data.hasOwnProperty('has_permission_incompatibility')) {
                obj['has_permission_incompatibility'] = ApiClient.convertToType(data['has_permission_incompatibility'], 'Boolean');
            }
            if (data.hasOwnProperty('has_type_incompatibility')) {
                obj['has_type_incompatibility'] = ApiClient.convertToType(data['has_type_incompatibility'], 'Boolean');
            }
            if (data.hasOwnProperty('has_unlinked_variable')) {
                obj['has_unlinked_variable'] = ApiClient.convertToType(data['has_unlinked_variable'], 'Boolean');
            }
            if (data.hasOwnProperty('height')) {
                obj['height'] = ApiClient.convertToType(data['height'], 'Number');
            }
            if (data.hasOwnProperty('height_mobile')) {
                obj['height_mobile'] = ApiClient.convertToType(data['height_mobile'], 'Number');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('options')) {
                obj['options'] = ApiClient.convertToType(data['options'], {'String': Object});
            }
            if (data.hasOwnProperty('page_id')) {
                obj['page_id'] = ApiClient.convertToType(data['page_id'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('variables')) {
                obj['variables'] = ApiClient.convertToType(data['variables'], [ArduinoLinkedvariable]);
            }
            if (data.hasOwnProperty('width')) {
                obj['width'] = ApiClient.convertToType(data['width'], 'Number');
            }
            if (data.hasOwnProperty('width_mobile')) {
                obj['width_mobile'] = ApiClient.convertToType(data['width_mobile'], 'Number');
            }
            if (data.hasOwnProperty('x')) {
                obj['x'] = ApiClient.convertToType(data['x'], 'Number');
            }
            if (data.hasOwnProperty('x_mobile')) {
                obj['x_mobile'] = ApiClient.convertToType(data['x_mobile'], 'Number');
            }
            if (data.hasOwnProperty('y')) {
                obj['y'] = ApiClient.convertToType(data['y'], 'Number');
            }
            if (data.hasOwnProperty('y_mobile')) {
                obj['y_mobile'] = ApiClient.convertToType(data['y_mobile'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ArduinoWidgetv3</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ArduinoWidgetv3</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ArduinoWidgetv3.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['page_id'] && !(typeof data['page_id'] === 'string' || data['page_id'] instanceof String)) {
            throw new Error("Expected the field `page_id` to be a primitive type in the JSON string but got " + data['page_id']);
        }
        // ensure the json data is a string
        if (data['type'] && !(typeof data['type'] === 'string' || data['type'] instanceof String)) {
            throw new Error("Expected the field `type` to be a primitive type in the JSON string but got " + data['type']);
        }
        if (data['variables']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['variables'])) {
                throw new Error("Expected the field `variables` to be an array in the JSON data but got " + data['variables']);
            }
            // validate the optional field `variables` (array)
            for (const item of data['variables']) {
                ArduinoLinkedvariable.validateJSON(item);
            };
        }

        return true;
    }


}

ArduinoWidgetv3.RequiredProperties = ["height", "id", "options", "page_id", "type", "width", "x", "y"];

/**
 * True if the linked variables permissions are incompatible with the widget
 * @member {Boolean} has_permission_incompatibility
 */
ArduinoWidgetv3.prototype['has_permission_incompatibility'] = undefined;

/**
 * True if the linked variables types are incompatible with the widget
 * @member {Boolean} has_type_incompatibility
 */
ArduinoWidgetv3.prototype['has_type_incompatibility'] = undefined;

/**
 * If it's true the widget is linked to a soft-deleted variable
 * @member {Boolean} has_unlinked_variable
 */
ArduinoWidgetv3.prototype['has_unlinked_variable'] = undefined;

/**
 * Widget current height for desktop
 * @member {Number} height
 */
ArduinoWidgetv3.prototype['height'] = undefined;

/**
 * Widget current height for mobile
 * @member {Number} height_mobile
 */
ArduinoWidgetv3.prototype['height_mobile'] = undefined;

/**
 * The UUID of the widget, set by client
 * @member {String} id
 */
ArduinoWidgetv3.prototype['id'] = undefined;

/**
 * The name of the widget
 * @member {String} name
 */
ArduinoWidgetv3.prototype['name'] = undefined;

/**
 * Widget options
 * @member {Object.<String, Object>} options
 */
ArduinoWidgetv3.prototype['options'] = undefined;

/**
 * The ID of the page the widget belongs to, \"0\" if it's in the main page
 * @member {String} page_id
 */
ArduinoWidgetv3.prototype['page_id'] = undefined;

/**
 * The type of the widget
 * @member {String} type
 */
ArduinoWidgetv3.prototype['type'] = undefined;

/**
 * ArduinoLinkedvariableCollection is the media type for an array of ArduinoLinkedvariable (default view)
 * @member {Array.<module:model/ArduinoLinkedvariable>} variables
 */
ArduinoWidgetv3.prototype['variables'] = undefined;

/**
 * Widget current width for desktop
 * @member {Number} width
 */
ArduinoWidgetv3.prototype['width'] = undefined;

/**
 * Widget current width for mobile
 * @member {Number} width_mobile
 */
ArduinoWidgetv3.prototype['width_mobile'] = undefined;

/**
 * Widget x position for desktop
 * @member {Number} x
 */
ArduinoWidgetv3.prototype['x'] = undefined;

/**
 * Widget x position for mobile
 * @member {Number} x_mobile
 */
ArduinoWidgetv3.prototype['x_mobile'] = undefined;

/**
 * Widget y position for desktop
 * @member {Number} y
 */
ArduinoWidgetv3.prototype['y'] = undefined;

/**
 * Widget y position for mobile
 * @member {Number} y_mobile
 */
ArduinoWidgetv3.prototype['y_mobile'] = undefined;






export default ArduinoWidgetv3;

