/**
 * Iot API
 * Collection of all public API endpoints.
 *
 * The version of the OpenAPI document: 2.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.1.2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.IotApi) {
      root.IotApi = {};
    }
    root.IotApi.ArduinoSeriesResponse = factory(root.IotApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The ArduinoSeriesResponse model module.
   * @module model/ArduinoSeriesResponse
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>ArduinoSeriesResponse</code>.
   * ArduinoSeriesResponse media type (default view)
   * @alias module:model/ArduinoSeriesResponse
   * @class
   * @param countValues {Number} Total number of values in the array 'values'
   * @param fromDate {Date} From date
   * @param interval {Number} Resolution in seconds
   * @param query {String} Query of for the data
   * @param respVersion {Number} Response version
   * @param status {String} Status of the response
   * @param times {Array.<Date>} Timestamp in RFC3339
   * @param toDate {Date} To date
   * @param values {Array.<Number>} Values in Float
   */
  var exports = function(countValues, fromDate, interval, query, respVersion, status, times, toDate, values) {
    var _this = this;

    _this['count_values'] = countValues;
    _this['from_date'] = fromDate;
    _this['interval'] = interval;
    _this['query'] = query;
    _this['resp_version'] = respVersion;
    _this['status'] = status;
    _this['times'] = times;
    _this['to_date'] = toDate;
    _this['values'] = values;
  };

  /**
   * Constructs a <code>ArduinoSeriesResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ArduinoSeriesResponse} obj Optional instance to populate.
   * @return {module:model/ArduinoSeriesResponse} The populated <code>ArduinoSeriesResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('count_values')) {
        obj['count_values'] = ApiClient.convertToType(data['count_values'], 'Number');
      }
      if (data.hasOwnProperty('from_date')) {
        obj['from_date'] = ApiClient.convertToType(data['from_date'], 'Date');
      }
      if (data.hasOwnProperty('interval')) {
        obj['interval'] = ApiClient.convertToType(data['interval'], 'Number');
      }
      if (data.hasOwnProperty('message')) {
        obj['message'] = ApiClient.convertToType(data['message'], 'String');
      }
      if (data.hasOwnProperty('query')) {
        obj['query'] = ApiClient.convertToType(data['query'], 'String');
      }
      if (data.hasOwnProperty('resp_version')) {
        obj['resp_version'] = ApiClient.convertToType(data['resp_version'], 'Number');
      }
      if (data.hasOwnProperty('series_limit')) {
        obj['series_limit'] = ApiClient.convertToType(data['series_limit'], 'Number');
      }
      if (data.hasOwnProperty('status')) {
        obj['status'] = ApiClient.convertToType(data['status'], 'String');
      }
      if (data.hasOwnProperty('times')) {
        obj['times'] = ApiClient.convertToType(data['times'], ['Date']);
      }
      if (data.hasOwnProperty('to_date')) {
        obj['to_date'] = ApiClient.convertToType(data['to_date'], 'Date');
      }
      if (data.hasOwnProperty('values')) {
        obj['values'] = ApiClient.convertToType(data['values'], ['Number']);
      }
    }
    return obj;
  }

  /**
   * Total number of values in the array 'values'
   * @member {Number} count_values
   */
  exports.prototype['count_values'] = undefined;
  /**
   * From date
   * @member {Date} from_date
   */
  exports.prototype['from_date'] = undefined;
  /**
   * Resolution in seconds
   * @member {Number} interval
   */
  exports.prototype['interval'] = undefined;
  /**
   * If the response is different than 'ok'
   * @member {String} message
   * @default ''
   */
  exports.prototype['message'] = '';
  /**
   * Query of for the data
   * @member {String} query
   */
  exports.prototype['query'] = undefined;
  /**
   * Response version
   * @member {Number} resp_version
   */
  exports.prototype['resp_version'] = undefined;
  /**
   * Max of values
   * @member {Number} series_limit
   */
  exports.prototype['series_limit'] = undefined;
  /**
   * Status of the response
   * @member {String} status
   */
  exports.prototype['status'] = undefined;
  /**
   * Timestamp in RFC3339
   * @member {Array.<Date>} times
   */
  exports.prototype['times'] = undefined;
  /**
   * To date
   * @member {Date} to_date
   */
  exports.prototype['to_date'] = undefined;
  /**
   * Values in Float
   * @member {Array.<Number>} values
   */
  exports.prototype['values'] = undefined;



  return exports;
}));


