/**
 * Arduino IoT Cloud API
 * Provides a set of endpoints to manage Arduino IoT Cloud **Devices**, **Things**, **Properties** and **Timeseries**. This API can be called just with any HTTP Client, or using one of these clients:  * [Javascript NPM package](https://www.npmjs.com/package/@arduino/arduino-iot-client)  * [Python PYPI Package](https://pypi.org/project/arduino-iot-client/)  * [Golang Module](https://github.com/arduino/iot-client-go)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ArduinoLoradevicev1 model module.
 * @module model/ArduinoLoradevicev1
 * @version 2.0.6
 */
class ArduinoLoradevicev1 {
    /**
     * Constructs a new <code>ArduinoLoradevicev1</code>.
     * ArduinoLoradevicev1 media type (default view)
     * @alias module:model/ArduinoLoradevicev1
     * @param appEui {String} The eui of the app
     * @param appKey {String} The key of the device
     * @param deviceId {String} The id of the device
     * @param eui {String} The eui of the lora device
     */
    constructor(appEui, appKey, deviceId, eui) { 
        
        ArduinoLoradevicev1.initialize(this, appEui, appKey, deviceId, eui);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, appEui, appKey, deviceId, eui) { 
        obj['app_eui'] = appEui;
        obj['app_key'] = appKey;
        obj['device_id'] = deviceId;
        obj['eui'] = eui;
    }

    /**
     * Constructs a <code>ArduinoLoradevicev1</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ArduinoLoradevicev1} obj Optional instance to populate.
     * @return {module:model/ArduinoLoradevicev1} The populated <code>ArduinoLoradevicev1</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ArduinoLoradevicev1();

            if (data.hasOwnProperty('app_eui')) {
                obj['app_eui'] = ApiClient.convertToType(data['app_eui'], 'String');
            }
            if (data.hasOwnProperty('app_key')) {
                obj['app_key'] = ApiClient.convertToType(data['app_key'], 'String');
            }
            if (data.hasOwnProperty('device_id')) {
                obj['device_id'] = ApiClient.convertToType(data['device_id'], 'String');
            }
            if (data.hasOwnProperty('eui')) {
                obj['eui'] = ApiClient.convertToType(data['eui'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ArduinoLoradevicev1</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ArduinoLoradevicev1</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ArduinoLoradevicev1.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['app_eui'] && !(typeof data['app_eui'] === 'string' || data['app_eui'] instanceof String)) {
            throw new Error("Expected the field `app_eui` to be a primitive type in the JSON string but got " + data['app_eui']);
        }
        // ensure the json data is a string
        if (data['app_key'] && !(typeof data['app_key'] === 'string' || data['app_key'] instanceof String)) {
            throw new Error("Expected the field `app_key` to be a primitive type in the JSON string but got " + data['app_key']);
        }
        // ensure the json data is a string
        if (data['device_id'] && !(typeof data['device_id'] === 'string' || data['device_id'] instanceof String)) {
            throw new Error("Expected the field `device_id` to be a primitive type in the JSON string but got " + data['device_id']);
        }
        // ensure the json data is a string
        if (data['eui'] && !(typeof data['eui'] === 'string' || data['eui'] instanceof String)) {
            throw new Error("Expected the field `eui` to be a primitive type in the JSON string but got " + data['eui']);
        }

        return true;
    }


}

ArduinoLoradevicev1.RequiredProperties = ["app_eui", "app_key", "device_id", "eui"];

/**
 * The eui of the app
 * @member {String} app_eui
 */
ArduinoLoradevicev1.prototype['app_eui'] = undefined;

/**
 * The key of the device
 * @member {String} app_key
 */
ArduinoLoradevicev1.prototype['app_key'] = undefined;

/**
 * The id of the device
 * @member {String} device_id
 */
ArduinoLoradevicev1.prototype['device_id'] = undefined;

/**
 * The eui of the lora device
 * @member {String} eui
 */
ArduinoLoradevicev1.prototype['eui'] = undefined;






export default ArduinoLoradevicev1;

