/**
 * Arduino IoT Cloud API
 * Provides a set of endpoints to manage Arduino IoT Cloud **Devices**, **Things**, **Properties** and **Timeseries**. This API can be called just with any HTTP Client, or using one of these clients:  * [Javascript NPM package](https://www.npmjs.com/package/@arduino/arduino-iot-client)  * [Python PYPI Package](https://pypi.org/project/arduino-iot-client/)  * [Golang Module](https://github.com/arduino/iot-client-go)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ArduinoDevicev2 from './ArduinoDevicev2';

/**
 * The ArduinoLinkedDevice model module.
 * @module model/ArduinoLinkedDevice
 * @version 3.0.0
 */
class ArduinoLinkedDevice {
    /**
     * Constructs a new <code>ArduinoLinkedDevice</code>.
     * ArduinoLinked_device media type (default view)
     * @alias module:model/ArduinoLinkedDevice
     * @param device {module:model/ArduinoDevicev2} 
     * @param status {module:model/ArduinoLinkedDevice.StatusEnum} The status of the linked device
     */
    constructor(device, status) { 
        
        ArduinoLinkedDevice.initialize(this, device, status);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, device, status) { 
        obj['device'] = device;
        obj['status'] = status;
    }

    /**
     * Constructs a <code>ArduinoLinkedDevice</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ArduinoLinkedDevice} obj Optional instance to populate.
     * @return {module:model/ArduinoLinkedDevice} The populated <code>ArduinoLinkedDevice</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ArduinoLinkedDevice();

            if (data.hasOwnProperty('device')) {
                obj['device'] = ArduinoDevicev2.constructFromObject(data['device']);
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ArduinoLinkedDevice</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ArduinoLinkedDevice</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ArduinoLinkedDevice.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `device`
        if (data['device']) { // data not null
          ArduinoDevicev2.validateJSON(data['device']);
        }
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }

        return true;
    }


}

ArduinoLinkedDevice.RequiredProperties = ["device", "status"];

/**
 * @member {module:model/ArduinoDevicev2} device
 */
ArduinoLinkedDevice.prototype['device'] = undefined;

/**
 * The status of the linked device
 * @member {module:model/ArduinoLinkedDevice.StatusEnum} status
 */
ArduinoLinkedDevice.prototype['status'] = undefined;





/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
ArduinoLinkedDevice['StatusEnum'] = {

    /**
     * value: "OK"
     * @const
     */
    "OK": "OK",

    /**
     * value: "DELETED"
     * @const
     */
    "DELETED": "DELETED"
};



export default ArduinoLinkedDevice;

