/**
 * Iot API
 * Collection of all public API endpoints.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BatchQueryResponseSeriesMediaV1 model module.
 * @module model/BatchQueryResponseSeriesMediaV1
 * @version 0.0.1
 */
class BatchQueryResponseSeriesMediaV1 {
    /**
     * Constructs a new <code>BatchQueryResponseSeriesMediaV1</code>.
     * @alias module:model/BatchQueryResponseSeriesMediaV1
     * @param aggr {String} Aggregation type
     * @param expression {String} Query
     * @param metric {String} Metric name
     */
    constructor(aggr, expression, metric) { 
        
        BatchQueryResponseSeriesMediaV1.initialize(this, aggr, expression, metric);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, aggr, expression, metric) { 
        obj['aggr'] = aggr;
        obj['expression'] = expression;
        obj['metric'] = metric;
    }

    /**
     * Constructs a <code>BatchQueryResponseSeriesMediaV1</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BatchQueryResponseSeriesMediaV1} obj Optional instance to populate.
     * @return {module:model/BatchQueryResponseSeriesMediaV1} The populated <code>BatchQueryResponseSeriesMediaV1</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BatchQueryResponseSeriesMediaV1();

            if (data.hasOwnProperty('aggr')) {
                obj['aggr'] = ApiClient.convertToType(data['aggr'], 'String');
            }
            if (data.hasOwnProperty('expression')) {
                obj['expression'] = ApiClient.convertToType(data['expression'], 'String');
            }
            if (data.hasOwnProperty('metric')) {
                obj['metric'] = ApiClient.convertToType(data['metric'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Aggregation type
 * @member {String} aggr
 */
BatchQueryResponseSeriesMediaV1.prototype['aggr'] = undefined;

/**
 * Query
 * @member {String} expression
 */
BatchQueryResponseSeriesMediaV1.prototype['expression'] = undefined;

/**
 * Metric name
 * @member {String} metric
 */
BatchQueryResponseSeriesMediaV1.prototype['metric'] = undefined;






export default BatchQueryResponseSeriesMediaV1;

