/**
 * Iot API
 * Collection of all public API endpoints.
 *
 * The version of the OpenAPI document: 2.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.1.2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.IotApi) {
      root.IotApi = {};
    }
    root.IotApi.BatchQueryRawLastValueRequestMediaV1 = factory(root.IotApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The BatchQueryRawLastValueRequestMediaV1 model module.
   * @module model/BatchQueryRawLastValueRequestMediaV1
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>BatchQueryRawLastValueRequestMediaV1</code>.
   * @alias module:model/BatchQueryRawLastValueRequestMediaV1
   * @class
   * @param propertyId {String} Property id
   * @param thingId {String} Thing id
   */
  var exports = function(propertyId, thingId) {
    var _this = this;

    _this['property_id'] = propertyId;
    _this['thing_id'] = thingId;
  };

  /**
   * Constructs a <code>BatchQueryRawLastValueRequestMediaV1</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BatchQueryRawLastValueRequestMediaV1} obj Optional instance to populate.
   * @return {module:model/BatchQueryRawLastValueRequestMediaV1} The populated <code>BatchQueryRawLastValueRequestMediaV1</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('property_id')) {
        obj['property_id'] = ApiClient.convertToType(data['property_id'], 'String');
      }
      if (data.hasOwnProperty('thing_id')) {
        obj['thing_id'] = ApiClient.convertToType(data['thing_id'], 'String');
      }
    }
    return obj;
  }

  /**
   * Property id
   * @member {String} property_id
   */
  exports.prototype['property_id'] = undefined;
  /**
   * Thing id
   * @member {String} thing_id
   */
  exports.prototype['thing_id'] = undefined;



  return exports;
}));


