/**
 * Iot API
 * Collection of all public API endpoints.
 *
 * The version of the OpenAPI document: 2.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.1.2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/BatchQueryRawLastValueRequestMediaV1'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./BatchQueryRawLastValueRequestMediaV1'));
  } else {
    // Browser globals (root is window)
    if (!root.IotApi) {
      root.IotApi = {};
    }
    root.IotApi.BatchLastValueRequestsMediaV1 = factory(root.IotApi.ApiClient, root.IotApi.BatchQueryRawLastValueRequestMediaV1);
  }
}(this, function(ApiClient, BatchQueryRawLastValueRequestMediaV1) {
  'use strict';



  /**
   * The BatchLastValueRequestsMediaV1 model module.
   * @module model/BatchLastValueRequestsMediaV1
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>BatchLastValueRequestsMediaV1</code>.
   * @alias module:model/BatchLastValueRequestsMediaV1
   * @class
   * @param requests {Array.<module:model/BatchQueryRawLastValueRequestMediaV1>} Requests
   */
  var exports = function(requests) {
    var _this = this;

    _this['requests'] = requests;
  };

  /**
   * Constructs a <code>BatchLastValueRequestsMediaV1</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BatchLastValueRequestsMediaV1} obj Optional instance to populate.
   * @return {module:model/BatchLastValueRequestsMediaV1} The populated <code>BatchLastValueRequestsMediaV1</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('requests')) {
        obj['requests'] = ApiClient.convertToType(data['requests'], [BatchQueryRawLastValueRequestMediaV1]);
      }
    }
    return obj;
  }

  /**
   * Requests
   * @member {Array.<module:model/BatchQueryRawLastValueRequestMediaV1>} requests
   */
  exports.prototype['requests'] = undefined;



  return exports;
}));


