/**
 * Iot API
 * Collection of all public API endpoints.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ArduinoSeriesBatch from '../model/ArduinoSeriesBatch';
import ArduinoSeriesRawBatch from '../model/ArduinoSeriesRawBatch';
import BatchQueryRawRequestsMediaV1 from '../model/BatchQueryRawRequestsMediaV1';
import BatchQueryRequestsMediaV1 from '../model/BatchQueryRequestsMediaV1';
import Error from '../model/Error';

/**
* SeriesV1 service.
* @module api/SeriesV1Api
* @version 0.0.1
*/
export default class SeriesV1Api {

    /**
    * Constructs a new SeriesV1Api. 
    * @alias module:api/SeriesV1Api
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the seriesV1BatchQuery operation.
     * @callback module:api/SeriesV1Api~seriesV1BatchQueryCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ArduinoSeriesBatch} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * batch_query series_v1
     * Returns the batch of time-series data
     * @param {module:model/BatchQueryRequestsMediaV1} batchQueryRequestsMediaV1 
     * @param {module:api/SeriesV1Api~seriesV1BatchQueryCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ArduinoSeriesBatch}
     */
    seriesV1BatchQuery(batchQueryRequestsMediaV1, callback) {
      let postBody = batchQueryRequestsMediaV1;
      // verify the required parameter 'batchQueryRequestsMediaV1' is set
      if (batchQueryRequestsMediaV1 === undefined || batchQueryRequestsMediaV1 === null) {
        throw new Error("Missing the required parameter 'batchQueryRequestsMediaV1' when calling seriesV1BatchQuery");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = ['application/json'];
      let accepts = ['application/vnd.arduino.series.batch+json', 'application/vnd.goa.error+json'];
      let returnType = ArduinoSeriesBatch;
      return this.apiClient.callApi(
        '/v1/series/batch_query', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the seriesV1BatchQueryRaw operation.
     * @callback module:api/SeriesV1Api~seriesV1BatchQueryRawCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ArduinoSeriesRawBatch} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * batch_query_raw series_v1
     * Returns the batch of time-series data raw
     * @param {module:model/BatchQueryRawRequestsMediaV1} batchQueryRawRequestsMediaV1 
     * @param {module:api/SeriesV1Api~seriesV1BatchQueryRawCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ArduinoSeriesRawBatch}
     */
    seriesV1BatchQueryRaw(batchQueryRawRequestsMediaV1, callback) {
      let postBody = batchQueryRawRequestsMediaV1;
      // verify the required parameter 'batchQueryRawRequestsMediaV1' is set
      if (batchQueryRawRequestsMediaV1 === undefined || batchQueryRawRequestsMediaV1 === null) {
        throw new Error("Missing the required parameter 'batchQueryRawRequestsMediaV1' when calling seriesV1BatchQueryRaw");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = ['application/json'];
      let accepts = ['application/vnd.arduino.series.raw.batch+json', 'application/vnd.goa.error+json'];
      let returnType = ArduinoSeriesRawBatch;
      return this.apiClient.callApi(
        '/v1/series/batch_query_raw', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
