/**
 * Iot API
 * Collection of all public API endpoints.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.IotApi);
  }
}(this, function(expect, IotApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new IotApi.ArduinoDevicev2propertyvalueValue();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ArduinoDevicev2propertyvalueValue', function() {
    it('should create an instance of ArduinoDevicev2propertyvalueValue', function() {
      // uncomment below and update the code to test ArduinoDevicev2propertyvalueValue
      //var instane = new IotApi.ArduinoDevicev2propertyvalueValue();
      //expect(instance).to.be.a(IotApi.ArduinoDevicev2propertyvalueValue);
    });

    it('should have the property payload (base name: "payload")', function() {
      // uncomment below and update the code to test the property payload
      //var instane = new IotApi.ArduinoDevicev2propertyvalueValue();
      //expect(instance).to.be();
    });

    it('should have the property seqno (base name: "seqno")', function() {
      // uncomment below and update the code to test the property seqno
      //var instane = new IotApi.ArduinoDevicev2propertyvalueValue();
      //expect(instance).to.be();
    });

    it('should have the property statistics (base name: "statistics")', function() {
      // uncomment below and update the code to test the property statistics
      //var instane = new IotApi.ArduinoDevicev2propertyvalueValue();
      //expect(instance).to.be();
    });

  });

}));
