/**
 * Iot API
 * Collection of all public API endpoints.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.IotApi);
  }
}(this, function(expect, IotApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new IotApi.Property();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Property', function() {
    it('should create an instance of Property', function() {
      // uncomment below and update the code to test Property
      //var instane = new IotApi.Property();
      //expect(instance).to.be.a(IotApi.Property);
    });

    it('should have the property maxValue (base name: "max_value")', function() {
      // uncomment below and update the code to test the property maxValue
      //var instane = new IotApi.Property();
      //expect(instance).to.be();
    });

    it('should have the property minValue (base name: "min_value")', function() {
      // uncomment below and update the code to test the property minValue
      //var instane = new IotApi.Property();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new IotApi.Property();
      //expect(instance).to.be();
    });

    it('should have the property permission (base name: "permission")', function() {
      // uncomment below and update the code to test the property permission
      //var instane = new IotApi.Property();
      //expect(instance).to.be();
    });

    it('should have the property persist (base name: "persist")', function() {
      // uncomment below and update the code to test the property persist
      //var instane = new IotApi.Property();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instane = new IotApi.Property();
      //expect(instance).to.be();
    });

    it('should have the property updateParameter (base name: "update_parameter")', function() {
      // uncomment below and update the code to test the property updateParameter
      //var instane = new IotApi.Property();
      //expect(instance).to.be();
    });

    it('should have the property updateStrategy (base name: "update_strategy")', function() {
      // uncomment below and update the code to test the property updateStrategy
      //var instane = new IotApi.Property();
      //expect(instance).to.be();
    });

    it('should have the property variableName (base name: "variable_name")', function() {
      // uncomment below and update the code to test the property variableName
      //var instane = new IotApi.Property();
      //expect(instance).to.be();
    });

  });

}));
