/**
 * Arduino IoT Cloud API
 * Provides a set of endpoints to manage Arduino IoT Cloud **Devices**, **Things**, **Properties** and **Timeseries**. This API can be called just with any HTTP Client, or using one of these clients:  * [Javascript NPM package](https://www.npmjs.com/package/@arduino/arduino-iot-client)  * [Python PYPI Package](https://pypi.org/project/arduino-iot-client/)  * [Golang Module](https://github.com/arduino/iot-client-go)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ArduinoIotClient);
  }
}(this, function(expect, ArduinoIotClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ArduinoIotClient.SeriesV2Api();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SeriesV2Api', function() {
    describe('seriesV2BatchQuery', function() {
      it('should call seriesV2BatchQuery successfully', function(done) {
        //uncomment below and update the code to test seriesV2BatchQuery
        //instance.seriesV2BatchQuery(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('seriesV2BatchQueryRaw', function() {
      it('should call seriesV2BatchQueryRaw successfully', function(done) {
        //uncomment below and update the code to test seriesV2BatchQueryRaw
        //instance.seriesV2BatchQueryRaw(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('seriesV2BatchQueryRawLastValue', function() {
      it('should call seriesV2BatchQueryRawLastValue successfully', function(done) {
        //uncomment below and update the code to test seriesV2BatchQueryRawLastValue
        //instance.seriesV2BatchQueryRawLastValue(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('seriesV2BatchQuerySampling', function() {
      it('should call seriesV2BatchQuerySampling successfully', function(done) {
        //uncomment below and update the code to test seriesV2BatchQuerySampling
        //instance.seriesV2BatchQuerySampling(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('seriesV2HistoricData', function() {
      it('should call seriesV2HistoricData successfully', function(done) {
        //uncomment below and update the code to test seriesV2HistoricData
        //instance.seriesV2HistoricData(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
