/**
 * Arduino IoT Cloud API
 * Provides a set of endpoints to manage Arduino IoT Cloud **Devices**, **Things**, **Properties** and **Timeseries**. This API can be called just with any HTTP Client, or using one of these clients:  * [Javascript NPM package](https://www.npmjs.com/package/@arduino/arduino-iot-client)  * [Python PYPI Package](https://pypi.org/project/arduino-iot-client/)  * [Golang Module](https://github.com/arduino/iot-client-go)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ArduinoIotClient);
  }
}(this, function(expect, ArduinoIotClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ArduinoIotClient.TriggersV1Api();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TriggersV1Api', function() {
    describe('actionsV1Create', function() {
      it('should call actionsV1Create successfully', function(done) {
        //uncomment below and update the code to test actionsV1Create
        //instance.actionsV1Create(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('actionsV1Delete', function() {
      it('should call actionsV1Delete successfully', function(done) {
        //uncomment below and update the code to test actionsV1Delete
        //instance.actionsV1Delete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('actionsV1List', function() {
      it('should call actionsV1List successfully', function(done) {
        //uncomment below and update the code to test actionsV1List
        //instance.actionsV1List(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('actionsV1Show', function() {
      it('should call actionsV1Show successfully', function(done) {
        //uncomment below and update the code to test actionsV1Show
        //instance.actionsV1Show(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('actionsV1Update', function() {
      it('should call actionsV1Update successfully', function(done) {
        //uncomment below and update the code to test actionsV1Update
        //instance.actionsV1Update(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('triggersV1Create', function() {
      it('should call triggersV1Create successfully', function(done) {
        //uncomment below and update the code to test triggersV1Create
        //instance.triggersV1Create(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('triggersV1Delete', function() {
      it('should call triggersV1Delete successfully', function(done) {
        //uncomment below and update the code to test triggersV1Delete
        //instance.triggersV1Delete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('triggersV1List', function() {
      it('should call triggersV1List successfully', function(done) {
        //uncomment below and update the code to test triggersV1List
        //instance.triggersV1List(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('triggersV1Patch', function() {
      it('should call triggersV1Patch successfully', function(done) {
        //uncomment below and update the code to test triggersV1Patch
        //instance.triggersV1Patch(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('triggersV1Show', function() {
      it('should call triggersV1Show successfully', function(done) {
        //uncomment below and update the code to test triggersV1Show
        //instance.triggersV1Show(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('triggersV1Template', function() {
      it('should call triggersV1Template successfully', function(done) {
        //uncomment below and update the code to test triggersV1Template
        //instance.triggersV1Template(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('triggersV1Update', function() {
      it('should call triggersV1Update successfully', function(done) {
        //uncomment below and update the code to test triggersV1Update
        //instance.triggersV1Update(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
