name: test

on:
  pull_request:
  push:
    branches:
        - master
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: Disable EOL conversions
        run: git config --global core.autocrlf false

      - name: Checkout
        uses: actions/checkout@master

      - name: Smoke test
        uses: actions/setup-node@v4
        with:
            node-version: '20'
      - run: npm install
      - run: npm run build
      - run: cd smoke_test
      - run: npm install request
      - run: npm install request-promise
      - run: ./node_modules/mocha/bin/mocha smoke_test/smoke_test.js
        env:
            CLIENT_ID: ${{ secrets.CLIENT_ID }}
            CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}